/**
 * Base Agent class for MDAP (Multi-Dimensional Agent Protocol)
 */

import type { Backend } from '../contracts/protocols';
import type { GenerateResponse } from '../contracts/models';
import { createRequest } from '../contracts/models';
import { nanoid } from 'nanoid';
import { z } from 'zod';
import type { Artifact } from './artifacts';

export const AgentConfigSchema = z.object({
  id: z.string().default(() => nanoid()),
  name: z.string().optional(),
  role: z.string().optional(),
  systemPrompt: z.string().optional(),
  backend: z.custom<Backend>(),
  temperature: z.number().min(0).max(2).default(0.7),
  maxTokens: z.number().int().positive().default(4096),
  metadata: z.record(z.unknown()).default({}),
});

export type AgentConfig = z.infer<typeof AgentConfigSchema>;

export interface AgentTask {
  id: string;
  prompt: string;
  context?: Record<string, unknown>;
  parentTaskId?: string;
  metadata?: Record<string, unknown>;
  /** Previous agent outputs (context accumulation) */
  previousOutputs?: string[];
  /** Existing artifacts from previous agents */
  existingArtifacts?: Artifact[];
}

export interface AgentResult {
  taskId: string;
  agentId: string;
  output: string;
  response: GenerateResponse;
  /** Artifacts generated by this agent */
  artifacts?: Artifact[];
  metadata?: Record<string, unknown>;
}

export class Agent {
  public readonly id: string;
  public readonly name?: string;
  public readonly role?: string;
  protected config: AgentConfig;
  protected backend: Backend;
  protected conversationHistory: Array<{ role: string; content: string }> = [];

  constructor(config: AgentConfig) {
    this.config = AgentConfigSchema.parse(config);
    this.id = this.config.id;
    this.name = this.config.name;
    this.role = this.config.role;
    this.backend = this.config.backend;
  }

  /**
   * Execute a task
   */
  async execute(task: AgentTask): Promise<AgentResult> {
    // Build enhanced prompt with context and artifacts
    let enhancedPrompt = task.prompt;

    // Add previous agent outputs (context accumulation)
    if (task.previousOutputs && task.previousOutputs.length > 0) {
      const contextSection = `\n\n## Context from Previous Agents\n\n${task.previousOutputs.map((output, i) => `**Agent ${i + 1} Output:**\n${output}`).join('\n\n---\n\n')}`;
      enhancedPrompt += contextSection;
    }

    // Add existing artifacts information
    if (task.existingArtifacts && task.existingArtifacts.length > 0) {
      const artifactsSection = `\n\n## Existing Artifacts\n\nThe following files have been created by previous agents:\n\n${task.existingArtifacts.map(a => `- **${a.path}** (${a.type}, v${a.version}) - ${a.metadata.description || 'No description'}`).join('\n')}`;
      enhancedPrompt += artifactsSection;
    }

    // Build the system prompt
    const systemPrompt = this.config.systemPrompt
      ? this.config.systemPrompt
      : this.role
      ? `You are a ${this.role} agent.`
      : undefined;

    // Create request
    const request = createRequest({
      prompt: enhancedPrompt,
      systemPrompt,
      history: this.conversationHistory,
      parameters: {
        temperature: this.config.temperature,
        maxTokens: this.config.maxTokens,
      },
      metadata: {
        agentId: this.id,
        agentName: this.name,
        agentRole: this.role,
        taskId: task.id,
        parentTaskId: task.parentTaskId,
        ...task.metadata,
      },
    });

    // Execute with backend
    const response = await this.backend.generate(request, { routedTo: this.id });

    // Update conversation history
    this.conversationHistory.push(
      { role: 'user', content: enhancedPrompt },
      { role: 'assistant', content: response.outputText }
    );

    // Return result (artifacts will be added by subclasses or orchestrator)
    return {
      taskId: task.id,
      agentId: this.id,
      output: response.outputText,
      response,
      artifacts: [],
      metadata: {
        role: this.role,
        name: this.name,
        ...task.metadata,
      },
    };
  }

  /**
   * Clear conversation history
   */
  clearHistory(): void {
    this.conversationHistory = [];
  }

  /**
   * Get conversation history
   */
  getHistory(): Array<{ role: string; content: string }> {
    return [...this.conversationHistory];
  }

  /**
   * Add to conversation history manually
   */
  addToHistory(role: string, content: string): void {
    this.conversationHistory.push({ role, content });
  }

  /**
   * Get agent info
   */
  getInfo(): {
    id: string;
    name?: string;
    role?: string;
    historyLength: number;
  } {
    return {
      id: this.id,
      name: this.name,
      role: this.role,
      historyLength: this.conversationHistory.length,
    };
  }
}

/**
 * Create an agent
 */
export function createAgent(config: AgentConfig): Agent {
  return new Agent(config);
}
